### PR TITLE
fetchFile step

### PR DESCRIPTION
**Pull request by mofm**
Add step fetchFile to fetch file from remote URL. supported protocols: http, https, ftp and sftp. Also supported http basic auth, ftp and sftp authentication.

Example:

```
steps:
  - name: pypyr.steps.fetchfile
    comment: fetch file from URL and save.
    in:
      fetchFile:
          url: https://www.example.com/files/file.tar.gz
          path: /home/user/Downloads
```

### CODE REVIEW

**Comment by yaythomas** [comment]
wow, thanks so much for this @mofm! This looks like a very nifty useful step. 🎉 

You're very right that pypyr absolutely needs something like this - I currently use `curl` or `wget` etc. with `pypyr.steps.cmd` for this sort of thing, but it's not ideal. So you've spotted exactly a good use case to fill 🙌 !

As it stands, though, and I hate to be the party pooper, but I have to pump the brakes a bit here.

I'm sure the step as it stands works great for your personal use-case, but http/s especially is a complicated topic and I want to be sure that we get it architecturally _right_ for everyone else too - partly to be sure that it is extensible enough as a foundation that we can build more cool things (#55) on top of it in the future, and also partly because I take pypyr semver pretty seriously and I try to maintain backwards compatibility as much as possible - which means that casually introducing something today leads to maintenance headaches in the future if it needs re-working to make other new things work.

Which is not to say we shouldn't add new things. I would just like to take a careful think about future use-cases and how it fits into the over-all ecosystem before rushing in a complicated new feature with its own set of dependencies. (You can see that I do this to myself also - see the ADRs for the process of evaluating options for architecturally significant decisions [docs/adr](https://github.com/pypyr/pypyr/tree/main/docs/adr).

pypyr maintains 100% test coverage, so this code would also need to be unit-tested thoroughly - which is a significant amount of work in itself gauging by the quick review I did (there's a lot of conditional & looping logic in there, conditional imports etc.) But please DON'T start with a lot of work doing unit tests on it as it is now, because I think the code itself probably could do with a pretty big refactor to make it fit as a foundation into the future path of pypyr.

So until my thoughts are clear on the subject, I don't want to mess you around and waste your time by pointing you in one direction and then another if it turns out I didn't think it through carefully enough.

I'm not exactly clear myself on where this _should_ go yet, and I would love to hear your thoughts since you have the experience of doing this step already, so please feel free to educate me, if you would! 

1. Did you have a particular reason for using stdlib `httpclient` rather than stdlib `urllib.request`? The reason I ask is that `urllib` wraps up a lot of the functionality that you had to code by hand instead (e.g 300 redirects). . . and also has some others that your stripped down "essentials only" implementation doesn't (proxies, cookies, data urls, 401 auth required, ssl context for certs, custom headers, checking download against content-length header, "localhost" special name etc.).
2. Rather than have one big monster class doing everything, I might well think of splitting it into modules `pypyr.http` and `pypyr.ftp` instead - the underlying functional calls are different enough that I'm not too sure we'd gain much by trying to put it all behind the same interface. (Also, in retrospect, I'm not too fond of the `utils` namespace - this was the result of me just looking for somewhere to put "random" things in the past, but now It think I prob should've tried to keep the namespace hierarchy flatter.)
3. Similarly, rather than one `fetchfile` step that tries to do everything, maybe have `pypyr.steps.httpget` (for generalised GET requests, and an option to save result to file or just directly to context) and `pypyr.steps.ftpget` or `ftpdownload` or similar. Part of me thinking this is then we can have some regularity if you have `pypyr.steps.ftpdownload` vs `pypyr.steps.ftpupload`, and `pypyr.steps.httpget` vs `pypyr.steps.httppost` vs `pypyr.steps.httpput` etc. Or maybe in the case of `http` you just need one `pypyr.steps.http` step with an input arg `method`.

what do you think?
I hope this is not discouraging - I don't mean to be! Thanks again for all your work, I really appreciate it & it is an exciting step in the right direction! This does look like very nifty, and I'll happily use & test it myself on my private pipelines until we've hardened it enough to become part of the pypyr core!

**Comment by mofm** [comment]
Hi @yaythomas ,

Thank you for your kindness. 

1. I chose to use the httplib(python3 - http.client) module because I didn't need complex functions. Also urllib uses it to handle URLs that use HTTP and HTTPS. [1] 
2.  May be possible. But I prefer to focus on fetching files rather than focusing on specific protocols. "fetchFile step" is already fetching  from generally used protocols. (it works like this on similar tools)
3. i think it would be more complicated to parse it into even smaller pieces. however, a separate modular structure may be considered for specific protocol operations.

I totally understand and appreciate your concerns. Maybe a more modular structure can be created. so it can be easier to add a new step and maintenance, backward compatibility. I will think more about it too. 

I'm little sick. Sorry I couldn't give a more detailed answer.

**Comment by yaythomas** [comment]
Thanks for your clarifications @mofm, this is helpful! I'm busy tidying up a pretty big commit myself (the configencodings branch), and I'll give this my full attention after that is done.

Hope you feel better soon!

**Comment by yaythomas** [comment]
Sorry I took a while to get back to you, the queue of pypyr work with config need doing 1st and then re-work of the cmd+shell step (coming soon, currently cleaning up and documenting!) ended up taking priority. So thank you for your patience, I really appreciate it!

I don't fully have answers for all the above, but some of my thoughts are a bit more settled:
1. I'm likely to go for `urllib` rather than `http.client`. Reasons:  
  -  I'd rather rely on the well-tested/known "wrapper" functionality in there than have to reimplement it ourselves in pypyr.
  - The "extra" functionality is going to be useful for more pipeline authors - proxies/cookies/http headers etc. I'd rather not bake a more restrictive use case into pypyr and then have difficulties in the future when trying to extend/enhance the functionality.

2. I'm likely to split out http vs ftp steps, rather than trying to do it in one big mono-step. Reasons:
  - When discussing the more "advanced" features (custom headers, cookies etc.) the protocols are sufficiently different that the same inputs won't apply to both, and (from experience) it gets annoying pretty quick from an input validation perspective when the same step is trying to cater for too many mutually exclusive conditions at the same time. I'd rather have each step's input remain intuitive and directly applicable/understandable within the step context.
  - In the case of ftp, some concept of session/connection and changing directory is prob going to be useful to download/upload multiple files at a time.
  - Certainly the sftp lib is deffo going to into its own separate project to install as an add-on (similar to pypyr-aws and pypyr-slack). I try hard to keep the pypyr core light - I don't want to make a habit of allowing any/every external dependency in if it's now essential to the core.
  - Also thinking of async http and making a separate plug-in for that at some point if it's not as easily do-able as it should be with stdlib.

3. I've not fully thought through what the step breakdown for each should be yet.
  - But I've a suspicion there's going to be `pypyr.steps.http` with a verb/action input defaulting to GET:
```yaml
- name: pypyr.steps.http
  in:
    http:
      verb: POST
      url: https://blah
      headers:
         BLAH_TOKEN: blahvalue
      body:
        key1: value1
      out: ./response.json
```
  - FTP is prob going to have an upload vs download step.
  - Warning this very provisional and likely to change. Feedback welcome!

So given all this, I'm going to close this PR because the amount of re-work that would be necessary is pretty much going to be an entirely fresh change-set. I can't promise how quickly I'm going to get to this, though, aforementioned next release for `cmd` and then async cmds is next on the roadmap. And then, at last, this - so reast assured it will happen, given time :-)

Thanks for all your effort, I really appreciate it - the step you've coded is truly cool for your use-case & I totally see the point of it! It's just not quite right for the pypyr core because I'm having to think of a broader scope of use-cases/features rather than just putting something "temporary" in that then ends up needing maintenance in itself in the future as it ends up being replaced by something else while keeping backwards compatibility.

If you don't mind, please don't delete your fork/branch, I'm sure your work will be useful to others as a guide/example! (certainly it will be useful to myself while I'm getting through the implementation to see how you solved the various problems!) 

Thanks again for contributing to pypyr! I hope we can work together in the future!

**Pull request closed without merging**
